<#
.SYNOPSIS
  Generate Rust #[interface] dual-interface definitions for Word's create-path
  interfaces from word-vtable.txt, so an early-bound .NET client's vtable calls
  land on real slots (Word's exact oVft order). Word counterpart of
  tools/comshim/gen-vtables.ps1 — but simpler: Word uses NO [lcid] params.
  Every slot is an E_NOTIMPL stub except the create-path members, which get a
  real signature forwarding to a hand-written vt_* handler in lib.rs.
#>
[CmdletBinding()]
param(
    [string]$Dump = "$PSScriptRoot\word-vtable.txt",
    [string]$Out  = "$PSScriptRoot\..\..\wordcomshim\src\gen_word.rs"
)
$ErrorActionPreference = 'Stop'

# dump interface name -> @{ trait; struct }.
$map = [ordered]@{
    '_Application' = @{ trait = 'IWordApp';   struct = 'Application' }
    'Documents'    = @{ trait = 'IDocuments'; struct = 'Documents' }
    '_Document'    = @{ trait = 'IWordDoc';   struct = 'DocumentObj' }
    'Selection'    = @{ trait = 'ISelection'; struct = 'Selection' }
    'Range'        = @{ trait = 'IWordRange'; struct = 'Range' }
}

$V = '*const VARIANT'
# N VARIANT params, the first `first` named, the rest _pK — SaveAs & friends.
function Vargs([int]$n, [string]$first) {
    $parts = @("$first`: $V")
    for ($i = 2; $i -le $n; $i++) { $parts += "_p$i`: $V" }
    $parts -join ', '
}

# slot -> @{ sig = <params after &self>; call = <expr returning HRESULT> }.
# [in] VARIANT* (Word's optional args) and [in] VARIANT alike are a pointer on
# x64, so `*const VARIANT`; [in] BSTR is the string pointer, `*const u16`.
$overrides = @{
    '_Application' = @{
        10  = @{ sig = "ret: *mut BSTR";            call = 'vt_app_name(self, ret)' }
        11  = @{ sig = "ret: *mut *mut c_void";     call = 'vt_app_documents(self, ret)' }
        13  = @{ sig = "ret: *mut *mut c_void";     call = 'vt_app_activedoc(self, ret)' }
        15  = @{ sig = "ret: *mut *mut c_void";     call = 'vt_app_selection(self, ret)' }
        33  = @{ sig = "ret: *mut i16";             call = 'vt_app_visible_get(self, ret)' }
        34  = @{ sig = "v: i16";                    call = 'vt_app_visible_put(self, v)' }
        35  = @{ sig = "ret: *mut BSTR";            call = 'vt_app_version(self, ret)' }
        120 = @{ sig = "_sc: $V, _of: $V, _rd: $V"; call = 'vt_app_quit(self)' }
    }
    'Documents' = @{
        8  = @{ sig = "ret: *mut i32";                                call = 'vt_docs_count(self, ret)' }
        12 = @{ sig = "index: $V, ret: *mut *mut c_void";             call = 'vt_docs_item(self, index, ret)' }
        17 = @{ sig = "_t: $V, _nt: $V, _dt: $V, _vis: $V, ret: *mut *mut c_void"; call = 'vt_docs_add(self, ret)' }
    }
    '_Document' = @{
        7   = @{ sig = "ret: *mut BSTR";                       call = 'vt_doc_name(self, ret)' }
        56  = @{ sig = "ret: *mut *mut c_void";                call = 'vt_doc_content(self, ret)' }
        167 = @{ sig = "_sc: $V, _of: $V, _rd: $V";            call = 'vt_doc_close(self)' }
        178 = @{ sig = "_start: $V, _end: $V, ret: *mut *mut c_void"; call = 'vt_doc_range(self, ret)' }
        297 = @{ sig = "$(Vargs 16 'filename')";               call = 'vt_doc_saveas(self, filename)' }
        434 = @{ sig = "$(Vargs 17 'filename')";               call = 'vt_doc_saveas(self, filename)' }
    }
    'Selection' = @{
        7   = @{ sig = "ret: *mut BSTR";        call = 'vt_sel_text_get(self, ret)' }
        8   = @{ sig = "v: *const u16";         call = 'vt_sel_text_put(self, v)' }
        57  = @{ sig = "ret: *mut *mut c_void"; call = 'vt_sel_range(self, ret)' }
        81  = @{ sig = "text: *const u16";      call = 'vt_sel_insertafter(self, text)' }
        134 = @{ sig = "text: *const u16";      call = 'vt_sel_typetext(self, text)' }
        137 = @{ sig = "";                      call = 'vt_sel_typepara(self)' }
    }
    'Range' = @{
        7   = @{ sig = "ret: *mut BSTR";   call = 'vt_rng_text_get(self, ret)' }
        8   = @{ sig = "v: *const u16";    call = 'vt_rng_text_put(self, v)' }
        99  = @{ sig = "text: *const u16"; call = 'vt_rng_insertafter(self, text)' }
        124 = @{ sig = "";                 call = 'vt_rng_insertpara(self)' }
    }
}

$lines = Get-Content -LiteralPath $Dump
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// @generated by tools/wordshim/gen-word-vtables.ps1 from the Word typelib. Do not edit.')
[void]$sb.AppendLine('// Full vtable slot lists (Word oVft order) as E_NOTIMPL stubs; real create-path')
[void]$sb.AppendLine('// members forward to vt_* handlers in lib.rs. include!d inside `mod win`.')
[void]$sb.AppendLine()

function Emit-Iface($sb, $trait, $iid, $struct, $slots, $ov) {
    [void]$sb.AppendLine("#[interface(`"$iid`")]")
    [void]$sb.AppendLine("unsafe trait $trait`: IDispatch {")
    foreach ($n in $slots) {
        $extra = if ($ov.ContainsKey($n) -and $ov[$n].sig) { ", $($ov[$n].sig)" } else { "" }
        [void]$sb.AppendLine("    unsafe fn s$n(&self$extra) -> HRESULT;")
    }
    [void]$sb.AppendLine("}")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine("impl ${trait}_Impl for ${struct}_Impl {")
    foreach ($n in $slots) {
        if ($ov.ContainsKey($n)) {
            $extra = if ($ov[$n].sig) { ", $($ov[$n].sig)" } else { "" }
            [void]$sb.AppendLine("    unsafe fn s$n(&self$extra) -> HRESULT { unsafe { $($ov[$n].call) } }")
        } else {
            [void]$sb.AppendLine("    unsafe fn s$n(&self) -> HRESULT { log(`"$trait vtable#$n unmodeled (early-bound)`"); E_NOTIMPL }")
        }
    }
    [void]$sb.AppendLine("}")
    [void]$sb.AppendLine()
}

foreach ($iface in $map.Keys) {
    $trait = $map[$iface].trait
    $struct = $map[$iface].struct
    $start = ($lines | Select-String -SimpleMatch "INTERFACE $iface " | Select-Object -First 1).LineNumber
    if (-not $start) { throw "interface $iface not found in dump" }
    if ($lines[$start - 1] -notmatch 'IID=\{([0-9A-Fa-f-]+)\}') { throw "no IID for $iface" }
    $iid = $Matches[1]

    $slots = @()
    for ($i = $start; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match '^INTERFACE ') { break }
        if ($lines[$i] -match '^\s*slot#(\d+)\s') { $n = [int]$Matches[1]; if ($n -ge 7) { $slots += $n } }
    }

    $ov = $overrides[$iface]
    if (-not $ov) { $ov = @{} }
    Emit-Iface $sb $trait $iid $struct $slots $ov
    Write-Host ("{0} -> {1} on {2}: {3} slots (7..{4}), {5} real" -f $iface, $trait, $struct, $slots.Count, ($slots[-1]), $ov.Count)
}

Set-Content -LiteralPath $Out -Value $sb.ToString() -Encoding UTF8
Write-Host "wrote $Out"
