<#
.SYNOPSIS
  Generate Rust #[interface] definitions for Excel's dual interfaces from the
  type-library dump, so an early-bound .NET client's vtable calls land on real
  slots (in Excel's exact order). Every slot is a stub returning E_NOTIMPL;
  real create-path methods are layered on by hand in main.rs.

.DESCRIPTION
  Reads tlb-dump.txt (produced from the live Excel typelib: one "slot#N ..." line
  per vtable entry, in oVft order). For each requested interface it emits, into
  xlcomshim/src/gen_excel.rs:
    - `#[interface("<iid>")] unsafe trait <Name>: IDispatch { unsafe fn s<slot>(&self) -> HRESULT; ... }`
      for slots 7..cFuncs-1 (0..6 are the inherited IUnknown+IDispatch slots).
    - `impl <Name>_Impl for <Struct>_Impl { unsafe fn s<slot>(&self) -> HRESULT { E_NOTIMPL } ... }`
  The generated file is `include!`d inside `mod win`, so it shares its imports.
#>
[CmdletBinding()]
param(
    [string]$Dump = "$env:LOCALAPPDATA\Temp\claude\C--Users-boris-source-docxy\72907cf6-fe7e-4b9c-9382-665f995312a1\scratchpad\tlb-dump.txt",
    [string]$Out
)
$ErrorActionPreference = 'Stop'
if (-not $Out) { $Out = Join-Path $PSScriptRoot '..\..\xlcomshim\src\gen_excel.rs' }

# dump interface name -> @{ trait = <Rust interface trait>; struct = <implementing struct> }
# Trait names are I-prefixed so they never collide with the struct names
# (Range/Font/Workbooks/Interior would otherwise clash). Note both `.Sheets` and
# `.Worksheets` return the same `Sheets` interface, implemented by our Worksheets.
$map = [ordered]@{
    '_Application' = @{ trait = 'IApplication'; struct = 'Application' }
    'Workbooks'    = @{ trait = 'IWorkbooks';   struct = 'Workbooks' }
    '_Workbook'    = @{ trait = 'IWorkbook';    struct = 'Workbook' }
    'Sheets'       = @{ trait = 'ISheets';      struct = 'Worksheets' }
    '_Worksheet'   = @{ trait = 'IWorksheet';   struct = 'Worksheet' }
    'Range'        = @{ trait = 'IRange';       struct = 'Range' }
    'Font'         = @{ trait = 'IFont';        struct = 'Font' }
    'Interior'     = @{ trait = 'IInterior';    struct = 'Interior' }
}

$lines = Get-Content -LiteralPath $Dump
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// @generated by tools/comshim/gen-vtables.ps1 from the Excel typelib. Do not edit.')
[void]$sb.AppendLine('// Full vtable slot lists (Excel oVft order) as E_NOTIMPL stubs; real methods')
[void]$sb.AppendLine('// are layered on in main.rs. include!d inside `mod win`.')
[void]$sb.AppendLine()

foreach ($iface in $map.Keys) {
    $trait  = $map[$iface].trait
    $struct = $map[$iface].struct
    # locate the interface header
    $start = ($lines | Select-String -SimpleMatch "INTERFACE $iface " | Select-Object -First 1).LineNumber
    if (-not $start) { throw "interface $iface not found in dump" }
    $header = $lines[$start - 1]
    if ($header -notmatch 'IID=\{([0-9A-Fa-f-]+)\}') { throw "no IID for $iface" }
    $iid = $Matches[1]

    # collect slot numbers >= 7 until the next INTERFACE/separator
    $slots = @()
    for ($i = $start; $i -lt $lines.Count; $i++) {
        $ln = $lines[$i]
        if ($ln -match '^INTERFACE ' -or $ln -match '^={5,}') { break }
        if ($ln -match '^\s*slot#(\d+)\s') {
            $n = [int]$Matches[1]
            if ($n -ge 7) { $slots += $n }
        }
    }

    [void]$sb.AppendLine("#[interface(`"$iid`")]")
    [void]$sb.AppendLine("unsafe trait $trait`: IDispatch {")
    foreach ($n in $slots) { [void]$sb.AppendLine("    unsafe fn s$n(&self) -> HRESULT;") }
    [void]$sb.AppendLine("}")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine("impl ${trait}_Impl for ${struct}_Impl {")
    foreach ($n in $slots) { [void]$sb.AppendLine("    unsafe fn s$n(&self) -> HRESULT { E_NOTIMPL }") }
    [void]$sb.AppendLine("}")
    [void]$sb.AppendLine()
    Write-Host ("{0} -> {1} on {2}: {3} slots (7..{4})" -f $iface, $trait, $struct, $slots.Count, ($slots[-1]))
}

Set-Content -LiteralPath $Out -Value $sb.ToString() -Encoding UTF8
Write-Host "wrote $Out"
