"""Regenerate opccore/src/codepage.rs from Windows code-page mappings.

Run on Windows with Python. MultiByteToWideChar supplies the exact mapping
RichEdit uses, including defined C1 values absent from Python's codecs.
Bytes Windows refuses or maps to U+FFFD remain 0 and are refused by the decoders.
"""

from ctypes import create_string_buffer, create_unicode_buffer, windll
from pathlib import Path


def table(page):
    decode = windll.kernel32.MultiByteToWideChar
    values = []
    for byte in range(128, 256):
        raw = create_string_buffer(bytes([byte]))
        wide = create_unicode_buffer(2)
        count = decode(page, 0, raw, 1, wide, 2)
        code = ord(wide[0]) if count == 1 else 0
        values.append(0 if code == 0xFFFD else code)
    return values


CHARSET_PAGE = r"""
/// The code page an RTF `\fcharset` names; `ansi_page` is the document's
/// `\ansicpg` (charset 1, DEFAULT_CHARSET). 42 is Windows' SYMBOL_CHARSET,
/// whose bytes are U+F000 + byte. `None` for a charset with no page here.
pub fn charset_page(charset: i32, ansi_page: i32) -> Option<i32> {
    Some(match charset {
        0 => 1252,
        1 => ansi_page,
        2 => 42,
        161 => 1253,
        162 => 1254,
        163 => 1258,
        177 => 1255,
        178 => 1256,
        186 => 1257,
        204 => 1251,
        222 => 874,
        238 => 1250,
        _ => return None,
    })
}"""


def main():
    lines = [
        "//! Windows single-byte code pages, for the legacy text formats that name one:",
        r"//! RTF `\'hh` escapes (mppread's task notes, docxcore's RTF import) and HTML",
        "//! saved as `windows-125x`.",
        "// Generated by corpus/tools/gen_rtf_codepages.py using MultiByteToWideChar.",
        "// Zero denotes a byte Windows cannot decode (or maps to U+FFFD).",
        "",
    ]
    pages = [874, *range(1250, 1259)]
    for page in pages:
        values = table(page)
        lines.append(f"const CP{page}: [u16; 128] = [")
        for i in range(0, 128, 8):
            lines.append("    " + ", ".join(f"0x{x:04x}" for x in values[i : i + 8]) + ",")
        lines.append("];\n")
    lines += [
        "/// The character `byte` stands for in Windows code page `page`. ASCII is",
        "/// itself in every page; `None` for a page not here (DBCS pages such as 932",
        "/// among them) or a byte the page leaves undefined.",
        "pub fn decode(page: i32, byte: u8) -> Option<char> {",
        "    if byte < 0x80 { return Some(char::from(byte)); }",
        "    let table = match page {",
    ]
    for page in pages:
        lines.append(f"        {page} => &CP{page},")
    lines += [
        "        _ => return None,",
        "    };",
        "    let code = table[(byte - 0x80) as usize];",
        "    (code != 0).then(|| char::from_u32(u32::from(code))).flatten()",
        "}",
        CHARSET_PAGE,
    ]
    path = Path(__file__).resolve().parents[2] / "opccore/src/codepage.rs"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
