"""Regenerate mppread/src/rtf_codepage.rs from Windows code-page mappings.

Run on Windows with Python. MultiByteToWideChar supplies the exact mapping
RichEdit uses, including defined C1 values absent from Python's codecs.
Bytes Windows refuses or maps to U+FFFD remain 0 and are refused by mppread.
"""

from ctypes import create_string_buffer, create_unicode_buffer, windll
from pathlib import Path


def table(page):
    decode = windll.kernel32.MultiByteToWideChar
    values = []
    for byte in range(128, 256):
        raw = create_string_buffer(bytes([byte]))
        wide = create_unicode_buffer(2)
        count = decode(page, 0, raw, 1, wide, 2)
        code = ord(wide[0]) if count == 1 else 0
        values.append(0 if code == 0xFFFD else code)
    return values


def main():
    lines = [
        "//! Windows single-byte code pages used by RTF Notes hex escapes.",
        "// Generated by corpus/tools/gen_rtf_codepages.py using MultiByteToWideChar.",
        "// Zero denotes a byte Windows cannot decode (or maps to U+FFFD).",
        "",
    ]
    for page in range(1250, 1259):
        values = table(page)
        lines.append(f"const CP{page}: [u16; 128] = [")
        for i in range(0, 128, 8):
            lines.append("    " + ", ".join(f"0x{x:04x}" for x in values[i : i + 8]) + ",")
        lines.append("];\n")
    lines += [
        "pub(super) fn decode(page: i32, byte: u8) -> Option<char> {",
        "    if byte < 0x80 { return Some(char::from(byte)); }",
        "    let table = match page {",
    ]
    for page in range(1250, 1259):
        lines.append(f"        {page} => &CP{page},")
    lines += [
        "        _ => return None,",
        "    };",
        "    let code = table[(byte - 0x80) as usize];",
        "    (code != 0).then(|| char::from_u32(u32::from(code))).flatten()",
        "}",
    ]
    path = Path(__file__).resolve().parents[2] / "mppread/src/rtf_codepage.rs"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
